baseURL = "https://mj.maku.blog/"
relativeurls = true
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses = true
languageCode = "ja-jp"
title = "まくまく麻雀ノート"
# googleAnalytics = "UA-63069513-5"
googleAnalytics = "G-MPC341NBMR"

[markup.goldmark.renderer]
  unsafe = true

[params]
  sidebarLogo = "img/site-logo-sidebar.png"
  image = "img/site-logo.png"
  facebookAppId = "727481858403810"
  Author = "まく"
  AmazonId = "maku04-22"
  CustomSearchId = "partner-pub-6317852277883092:5421923271"

[module]
  [[module.imports]]
    path = "github.com/maku77/hugo-module-maku-common"
  [[module.imports]]
    path = "github.com/maku77/hugo-theme-maku"

