name: Build and deploy website

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: maku77/en.maku.blog/.github/workflows/main.yml@main
